language: node_js
node_js:
  - '8'
#os: osx todo restore safari
install: ./build/npm-install.sh
before_install: if [[ `npm -v` != 6* ]]; then npm i -g npm; fi
script:
  - npm run deploy
after_script:
  - node ./node_modules/coveralls/bin/coveralls.js -v < ./reports/report-lcov/lcov.info
sudo: required
deploy:
  - provider: npm
    skip_cleanup: true
    email: comindware-awesome-bot@comindware.com
    api_key:
      secure: kUR32lu8J1pQ8+csFu79JuZ635AfLjPI9+lK8mKaHrBWQC1dLFAipIMp/54vL4p8NqnwmYr6AoMYOYmvmfuUN94IwLcn86xfzmLr0r+cmLftDjynDNQEHhey2yL26ksLrP+s3YSNgGNhWqOIQ7G75B9DaeopjyAAMlR564celWl/QABapV1naFTBnsTDTmp2HppmOGEEwtbY3XTdvyESHt4SuIJ7hGLKcnJg5izOculMB3MWp7KiNzMQsWV2Ee8MjUgaW+WfOQmTMijcoQQBbo8PZcAKDXE5cGlDtGCuHx+Xs8/bOEg9MJIHjb1/AVyEM3qSNuoOlaSATkDrne0+4m6DLYPpzqaMsX0E0Z4aMlLV0uiikkI3PwGRtuXaqvyf7IedydE66isfA0MlTDGXQkjf2m+5Lf7NIbUM0+/+KZ9OlKkkzcgCKhh/iXwKyglu3pV/D/9ppSmMcEegGEPKb6O6IHbdAtlUFgjrxifw7/EehkYlk8q1lmqkkiKBxC5/KAFwrtHkBo9jENpsKSBODy4Y8YMmABi2eLbL/68yvu73GYBTELpaI0P1KVBMG5WekE71kz9xnX3uA5vUQB5yn5SYpQsg91rXKm1Y8KIzovimkmMSeIE8/T98is0Z4hc58JXCuMZtb61CoLI3bm+sr4L5vp+buKpRv/D8VO2U1nQ=
    on:
      tags: true
      repo: comindware/core-ui
      branch: master
  - provider: script
    script: npm run deploy:pages
    skip_cleanup: true
    on:
      tags: true
      repo: comindware/core-ui
      branch: master
addons:
  firefox: "latest"