language: node_js
node_js:
  - '8'
install: ./build/npm-install.sh
script:
  - npm run deploy
after_script:
  - node ./node_modules/coveralls/bin/coveralls.js -v < ./reports/report-lcov/lcov.info
deploy:
  - provider: npm
    skip_cleanup: true
    email: vdmsmirnov@gmail.com
    api_key:
      secure: mOX+eVc8YuiaJa0ks1o3vekJRIH2pcxI5KtrFOfUe3+E14JwnKWUTkVPdSfV9LRS+LuhxFJV69P6sPu4pK9Cv7qXABNOHMd3q9juHYqeqbFr6I1iQm/KpO9H0leNe0UMCatv6NGWUMekxotDwZcf5dnLvVLroYhIoouB3gmmaba1rbGcqeLfs2kI2RUZYDpMLDq0rayGnhr54IM5K9R1OnQE9dwaCAw3v3nYug8q5I/tqiHqzncbJK84QbdhE1E/AGfNP8RJRYqqIz/4Qfmkc2CGifD94M6RAxU64yiDAssTt5QklFiumeUryxYErlysBy8YaGH4btRVK+CVZrIAFe5VYv+0vSyTUdmnvYrefj1koo39oGMhXYz2WndN/Tl1Z7YQALfmaKXiUmBG6ybtja3jFl1ve+Zz8aZHWOEo1S2qdtIJtsJuu9fjvXGV/iq+QtI9fXdAFYekrx0LDhqpYQLJVwHihZ3bc2XSYcw4UmRWju2/pa6sevQgcgG6e8ykrxlnSL+qfk04SIQiyqK1T29NoCcn7G/Z9xPqkwmMh9eonmKDk+fTDeT5D0QzK5wEp0IS/Nt/67BpE2p06y3iV7QqtWphIaaq8kBWFdYJU+9x+J8Py9jIjMwOPnPzkA9lWNNNrUyNE0HmlOLcksXnifbOjNLUPDzvjDJlXCgswh0=
    on:
      tags: true
      repo: comindware/core-ui
      branch: 1.4/release
  - provider: script
    script: npm run deploy:pages
    skip_cleanup: true
    on:
      tags: true
      repo: comindware/core-ui
      branch: 1.4/release
