language: node_js
cache:
  directories:
    - node_modules
    - demo/node_modules
node_js:
  - '7'
install: ./build/npm-install.sh
script:
  - npm run deploy
after_script:
  - node ./node_modules/coveralls/bin/coveralls.js -v < ./reports/report-lcov/lcov.info
deploy:
  - provider: npm
    email: Stanislav.Guryev@comindware.com
    skip_cleanup: true
    api_key:
      secure: Adfd8FaRWz+HKGEPf7qx3z+BA4Uc3JbZn37FH1mVutPjdyaoNZZ/ruNXFglJuK1rWJctijh/SQZX0NhyPTMvhLh37tLURI31+vV6pfQL7GLpohCjAgg32oJFw1gL9fkptReTEwNziY2CGRl5ltQNzHbevbEw+UTD/xnl469VzKX3Q164addrGGGPEkRGPTDigJAmi/vu6x8o8AH3yK8NnhT9xM32SS2GHTaTYZGQqHXAnhH51uP4yBYQotAgYRvKRsl+52qJ9uzWSq1w6LWLLlp7ECUoOhM6G41385jXS1gr1an0wXHgy+mHKjg6oTMJi4UmHhxaUFA6M5y4k/RTyFKtjcaxBBtIrCgenzQVqGuIjkEeckcxiz8n/poPW7ucuVMCWOzPGluj1Pjw0pKYRij2RoCySkg1/cceLzNkC8X0lbDJ7+ntVqJOgknU1kNNC1Kl/KsXLi2e1gXDb94Afai/Ncsq7HvVLAsnlNRHbidTYYQZbidSejlpnn2bKjjK+Ja7MHRs9QBKxDVW6QjPXtNUzZfuDbFHK6PhUlLROY+jZ6qtZN5nkFX5bBerQNmLTdmnSUQrH7Vd7Uq2fumf2yGWP5U7AMhkSSQJWME4wQobd/LCeM0wjJfCewoD/YS7t/BJ4R8XAgvPPtKoFnc/vIomfO0vtcgJQUlboPpBm9w=
    on:
      tags: true
      repo: stasguryev/core-ui
      branch: master
  - provider: script
    script: npm run deploy:pages
    skip_cleanup: true
    on:
      tags: true
      repo: stasguryev/core-ui
      branch: master