language: node_js
node_js:
  - '8'
#os: osx todo restore safari
install: ./build/npm-install.sh
before_install: if [[ `npm -v` != 6* ]]; then npm i -g npm; fi
script:
  - npm run deploy
after_script:
  - node ./node_modules/coveralls/bin/coveralls.js -v < ./reports/report-lcov/lcov.info
sudo: required
deploy:
  - provider: npm
    skip_cleanup: true
    email: comindware-awesome-bot@comindware.com
    api_key:
      secure: g/Y1i4Wwlu430wX9KVB0MkA7WpLp3grivh4x/I4jN1uxbJUfwrMIemaH2PZne53VvXVWEMCEY9yMBr83fyxtYlhavbW5VXEBuxdZSv1Aw2NNnBeDXj37Cdqs7alVudCz/qIJS3Ulv//tgjj2RmErUUDVgZtI7hDCf567UlphCBtV/ndPG+6eqwpcwczBEuLdPz6HyQBKclQ7IMUGvlsQFIGnUQPwpfL8T+Tk3Zqyb3X0JPspvj30vhVmvqKZFEzo690MVQrrIEknpYocmXHSY75a2z1b8CWhx0jbdriX6w/QYZUFRquhdXesrPNJTNP4UeJ/qaF+058dhJOwEev627z//guVyxZYxj8sYch1qQEQ3HvamWbMu6Ubc3hvxn9CSE9VuQWCs9V6Ad5G0gxNH1f8WHAEeOaL7H9ym33LHP14nTga7Vt4kagejUNQBJwRErbNRl66W24X/w2t+q/sby6FoGFWB0hkUpxMYuUSJ5MXcwi9jP5TQR4GSWsOQb/IUxCxlOevSQ/LqNmoN7XaRQERY/5t7/0NM8dKEbL6PJbSa0MU1Z8BmNgOn83vrdTkwy41FAWfoUBjYKBpJxjQFLQgVYeq25iPTgrfilLYkgyWASEJTLclE6NRZ9ZnX51ohnnU6y7LlaqNONgyExG/zb34i1RSRQiMacrmSEUhTzc=
    on:
      tags: true
      repo: comindware/core-ui
      branch: master
  - provider: script
    script: npm run deploy:pages
    skip_cleanup: true
    on:
      tags: true
      repo: comindware/core-ui
      branch: master
addons:
  firefox: "latest"